Repository UMCCMAP/server, pull requests merged in 2023-08, with the labels that each got.

#27 [Feat/login nickname/#23] 닉네임 받기 구현
  cmap/src/main/java/com/umc/cmap/config/oauth/SecurityConfig.java
  cmap/src/main/java/com/umc/cmap/domain/user/entity/Profile.java
  cmap/src/main/java/com/umc/cmap/domain/user/entity/User.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/controller/LoginController.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/dto/OAuthAttributes.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/service/CustomOAuth2UserService.java
  cmap/src/main/java/com/umc/cmap/domain/user/repository/UserRepository.java
Labels: ✨ Feature

#28 [Feat/filter/#21] 카페 필터구현
  cmap/src/main/java/com/umc/cmap/config/BaseResponseStatus.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/controller/CafeController.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/entity/Cafe.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/repository/CafeRepository.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/service/CafeService.java
  cmap/src/main/java/com/umc/cmap/domain/filter/dto/CafeFilterDto.java
  cmap/src/main/java/com/umc/cmap/domain/filter/entity/CafeFilter.java
  cmap/src/main/java/com/umc/cmap/domain/filter/entity/Filter.java
  cmap/src/main/java/com/umc/cmap/domain/filter/repository/CafeFilterRepository.java
  cmap/src/main/java/com/umc/cmap/domain/filter/repository/FilterRepository.java
  cmap/src/main/java/com/umc/cmap/domain/filter/service/CafeFilterService.java
  cmap/src/main/java/com/umc/cmap/domain/filter/service/FilterService.java
  cmap/src/main/java/com/umc/cmap/domain/theme/controller/CafeThemeController.java
  cmap/src/main/java/com/umc/cmap/domain/theme/controller/ThemeController.java
  cmap/src/main/java/com/umc/cmap/domain/theme/entity/CafeTheme.java
  cmap/src/main/java/com/umc/cmap/domain/theme/entity/Theme.java
  cmap/src/main/java/com/umc/cmap/domain/theme/service/CafeThemeService.java
  cmap/src/main/java/com/umc/cmap/domain/theme/service/ThemeService.java
Labels: ✨ Feature

#32 [Feat/board comment/#31] 게시글 - 댓글 관련 기능 구현
  cmap/src/main/java/com/umc/cmap/domain/comment/controller/CommentController.java
  cmap/src/main/java/com/umc/cmap/domain/comment/dto/CommentRequest.java
  cmap/src/main/java/com/umc/cmap/domain/comment/dto/CommentResponse.java
  cmap/src/main/java/com/umc/cmap/domain/comment/dto/UpdateCommentRequest.java
  cmap/src/main/java/com/umc/cmap/domain/comment/entity/Comment.java
  cmap/src/main/java/com/umc/cmap/domain/comment/mapper/CommentMapper.java
  cmap/src/main/java/com/umc/cmap/domain/comment/repository/CommentRepository.java
  cmap/src/main/java/com/umc/cmap/domain/comment/service/CommentService.java
Labels: ✨ Feature

#33 [(refactor,feat)/board/#25] 게시판 주요 기능 코드 수정 및 해시태그
  cmap/src/main/java/com/umc/cmap/config/BaseResponseStatus.java
  cmap/src/main/java/com/umc/cmap/domain/board/controller/BoardController.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardListResponse.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardModifyRequest.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardMyPostResponse.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardResponse.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardWriteRequest.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/TagDto.java
  cmap/src/main/java/com/umc/cmap/domain/board/entity/Board.java
  cmap/src/main/java/com/umc/cmap/domain/board/entity/BoardTag.java
  cmap/src/main/java/com/umc/cmap/domain/board/entity/Role.java
  cmap/src/main/java/com/umc/cmap/domain/board/entity/Tag.java
  cmap/src/main/java/com/umc/cmap/domain/board/repository/BoardRepository.java
  cmap/src/main/java/com/umc/cmap/domain/board/repository/BoardTagRepository.java
  cmap/src/main/java/com/umc/cmap/domain/board/repository/TagRepository.java
  cmap/src/main/java/com/umc/cmap/domain/board/service/BoardService.java
Labels: ✨ Feature, 🔨 Refactor

#35 [Refactor/review api/#34] 리뷰 관련 api 수정
  cmap/src/main/java/com/umc/cmap/domain/review/controller/ReviewController.java
  cmap/src/main/java/com/umc/cmap/domain/review/dto/ReviewResponse.java
  cmap/src/main/java/com/umc/cmap/domain/review/dto/ReviewWriterResponse.java
  cmap/src/main/java/com/umc/cmap/domain/review/entity/Review.java
  cmap/src/main/java/com/umc/cmap/domain/review/mapper/ReviewImageMapper.java
  cmap/src/main/java/com/umc/cmap/domain/review/mapper/ReviewMapper.java
  cmap/src/main/java/com/umc/cmap/domain/review/repository/ReviewRepository.java
  cmap/src/main/java/com/umc/cmap/domain/review/service/ReviewImageService.java
  cmap/src/main/java/com/umc/cmap/domain/review/service/ReviewService.java
  cmap/src/test/java/com/umc/cmap/domain/review/repository/ReviewRepositoryTest.java
  cmap/src/test/java/com/umc/cmap/domain/review/service/ReviewServiceTest.java
Labels: 🔨 Refactor

#37 [feat/board-like/#36] 게시글 좋아요 구현
  cmap/src/main/java/com/umc/cmap/config/BaseResponseStatus.java
  cmap/src/main/java/com/umc/cmap/domain/board/controller/BoardController.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/LikeBoardRequest.java
  cmap/src/main/java/com/umc/cmap/domain/board/entity/LikeBoard.java
  cmap/src/main/java/com/umc/cmap/domain/board/repository/LikeBoardRepository.java
  cmap/src/main/java/com/umc/cmap/domain/board/service/BoardService.java
Labels: ✨ Feature

#42 [Feat/mates/#39] 메이트 기능 구현
  cmap/src/main/java/com/umc/cmap/domain/user/entity/Mates.java
  cmap/src/main/java/com/umc/cmap/domain/user/entity/Profile.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/controller/LoginController.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/service/AuthService.java
  cmap/src/main/java/com/umc/cmap/domain/user/mates/controller/MatesController.java
  cmap/src/main/java/com/umc/cmap/domain/user/mates/service/MatesService.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/controller/ProfileController.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/dto/MatesInfoMapping.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/dto/ProfileRequest.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/dto/ProfileResponse.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/mapper/ProfileMapper.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/service/ProfileService.java
  cmap/src/main/java/com/umc/cmap/domain/user/repository/MatesRepository.java
  cmap/src/main/java/com/umc/cmap/domain/user/repository/ProfileRepository.java
  cmap/src/main/java/com/umc/cmap/domain/user/repository/UserRepository.java
  cmap/src/main/resources/application-oauth.yml
  cmap/src/test/java/com/umc/cmap/domain/profile/service/ProfileServiceTest.java
  cmap/src/test/resources/application-oauth.yml
  cmap/src/test/resources/application.yml
Labels: ✨ Feature

#43 [feat/board-search/#38] 게시글 검색 기능 구현
  cmap/src/main/java/com/umc/cmap/domain/board/controller/BoardController.java
  cmap/src/main/java/com/umc/cmap/domain/board/repository/BoardRepository.java
  cmap/src/main/java/com/umc/cmap/domain/board/service/BoardService.java
Labels: ✨ Feature

#47 Feat/review user/#40
  cmap/src/main/java/com/umc/cmap/domain/review/repository/ReviewRepository.java
  cmap/src/main/java/com/umc/cmap/domain/review/service/ReviewImageService.java
  cmap/src/main/java/com/umc/cmap/domain/review/service/ReviewService.java
  cmap/src/test/java/com/umc/cmap/domain/review/repository/ReviewRepositoryTest.java
  cmap/src/test/java/com/umc/cmap/domain/review/service/ReviewServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#51 [Feat/exception-handler/#50] EntityNotFoundException 핸들러 구현
  cmap/src/main/java/com/umc/cmap/config/excepion/ErrorResponse.java
  cmap/src/main/java/com/umc/cmap/config/excepion/ExceptionControllerAdvice.java
Labels: ✨ Feature

#52 [refactor/board-user/#46] authService 적용, 에러 수정 및 예외처리 핸들러 추가
  cmap/src/main/java/com/umc/cmap/config/BaseException.java
  cmap/src/main/java/com/umc/cmap/config/BaseResponseStatus.java
  cmap/src/main/java/com/umc/cmap/config/GlobalExceptionHandler.java
  cmap/src/main/java/com/umc/cmap/domain/board/controller/BoardController.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardModifyRequest.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardPostViewResponse.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardWriteRequest.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/LikeBoardRequest.java
  cmap/src/main/java/com/umc/cmap/domain/board/entity/LikeBoard.java
  cmap/src/main/java/com/umc/cmap/domain/board/repository/LikeBoardRepository.java
  cmap/src/main/java/com/umc/cmap/domain/board/service/BoardService.java
Labels: 🔨 Refactor

#58 [feat/board-add/#53] 게시글 프로필 이미지 추가 및 좋아요 하트 채우기 구현
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardPostViewResponse.java
  cmap/src/main/java/com/umc/cmap/domain/board/repository/BoardRepository.java
  cmap/src/main/java/com/umc/cmap/domain/board/repository/LikeBoardRepository.java
  cmap/src/main/java/com/umc/cmap/domain/board/service/BoardService.java
Labels: ✨ Feature

#59 [feat/board-add/#54] 메인화면 이미지 작업 및 프리뷰 구현
  cmap/src/main/java/com/umc/cmap/domain/board/controller/BoardController.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardModifyRequest.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardResponse.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardWriteRequest.java
  cmap/src/main/java/com/umc/cmap/domain/board/entity/BoardImage.java
  cmap/src/main/java/com/umc/cmap/domain/board/repository/BoardImageRepository.java
  cmap/src/main/java/com/umc/cmap/domain/board/service/BoardService.java
Labels: ✨ Feature

#61 [bugfix/correct-error/#61] 카페 관련 문제 엔티티 제거 및 comment warning 해결
  cmap/src/main/java/com/umc/cmap/domain/cafe/entity/CafeBasicExplain.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/entity/CafeExplain.java
  cmap/src/main/java/com/umc/cmap/domain/comment/entity/Comment.java
Labels: 🐞 BugFix

#62 [Feat/users/#48] JWT 추가 및 중복 처리, ProfileResponse 수정
  cmap/build.gradle
  cmap/src/main/java/com/umc/cmap/config/oauth/SecurityConfig.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/controller/LoginController.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/dto/OAuthAttributes.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/dto/UserRequest.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/mapper/UserRequestMapper.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/service/AuthService.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/service/CustomOAuth2UserService.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/token/OAuth2SuccessHandler.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/token/Token.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/token/TokenService.java
  cmap/src/main/java/com/umc/cmap/domain/user/mates/controller/MatesController.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/controller/ProfileController.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/dto/ProfileResponse.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/mapper/ProfileMapper.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/service/ProfileService.java
  cmap/src/test/java/com/umc/cmap/domain/profile/service/ProfileServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#64 [feat/cafe/#29] 카페 추천 구현 + 일부 기능 수정
  cmap/src/main/java/com/umc/cmap/domain/cafe/controller/CafeController.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/controller/response/CafeResponse.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/entity/Cafe.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/repository/CafeRepository.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/service/CafeService.java
  cmap/src/main/java/com/umc/cmap/domain/filter/service/CafeFilterService.java
  cmap/src/main/java/com/umc/cmap/domain/theme/controller/CafeThemeController.java
  cmap/src/main/java/com/umc/cmap/domain/theme/controller/ThemeController.java
  cmap/src/main/java/com/umc/cmap/domain/theme/controller/request/CafeThemeRequest.java
  cmap/src/main/java/com/umc/cmap/domain/theme/entity/CafeTheme.java
  cmap/src/main/java/com/umc/cmap/domain/theme/entity/Theme.java
Labels: ✨ Feature

#67 [(Bugfix, Refactor)/users/#63] 새 유저 디비 저장 및 코드 수정
  cmap/src/main/java/com/umc/cmap/config/oauth/SecurityConfig.java
  cmap/src/main/java/com/umc/cmap/domain/user/entity/Mates.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/controller/LoginController.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/dto/OAuthAttributes.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/service/AuthService.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/service/CustomOAuth2UserService.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/token/TokenService.java
  cmap/src/main/java/com/umc/cmap/domain/user/mates/controller/MatesController.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/controller/ProfileController.java
  cmap/src/main/java/com/umc/cmap/domain/user/repository/MatesRepository.java
Labels: 🐞 BugFix, 🔨 Refactor

#70 [feat/my-board/#68] 내가 쓴 게시글 구현 및 tagList 불필요한 데이터 삭제
  cmap/src/main/java/com/umc/cmap/domain/board/controller/BoardController.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardPostViewResponse.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardResponse.java
  cmap/src/main/java/com/umc/cmap/domain/board/repository/BoardRepository.java
  cmap/src/main/java/com/umc/cmap/domain/board/service/BoardService.java
Labels: ✨ Feature, 🔨 Refactor

#77 [Feat/review new/#69] 리뷰 제목, 키워드 기능 추가
  cmap/src/main/java/com/umc/cmap/domain/review/dto/ReviewRequest.java
  cmap/src/main/java/com/umc/cmap/domain/review/dto/ReviewResponse.java
  cmap/src/main/java/com/umc/cmap/domain/review/entity/Review.java
  cmap/src/main/java/com/umc/cmap/domain/review/mapper/ReviewMapper.java
  cmap/src/main/java/com/umc/cmap/domain/review/service/ReviewService.java
  cmap/src/test/java/com/umc/cmap/domain/review/service/ReviewServiceTest.java
Labels: ✨ Feature

#79 [feat/board-comment/#60] 댓글 기능 연동
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardPostViewResponse.java
  cmap/src/main/java/com/umc/cmap/domain/board/entity/Board.java
  cmap/src/main/java/com/umc/cmap/domain/board/service/BoardService.java
  cmap/src/main/java/com/umc/cmap/domain/comment/repository/CommentRepository.java
  cmap/src/main/java/com/umc/cmap/domain/comment/service/CommentService.java
  cmap/src/main/java/com/umc/cmap/file/S3Controller.java
Labels: ✨ Feature

#66 [refactor/cafe/#65] visited와 wantToVisit 관련 수정
  cmap/src/main/java/com/umc/cmap/domain/cafe/service/CafeService.java
Labels: 🔨 Refactor

#83 [Refactor/profile/#75] 유저별 리뷰 코드 수정
  cmap/src/main/java/com/umc/cmap/domain/user/profile/controller/ProfileController.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/service/ProfileService.java
Labels: 🔨 Refactor

#80 [Feat/cafe/#73] 엔티티 기능 추가/수정
  cmap/src/main/java/com/umc/cmap/config/BaseResponseStatus.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/controller/CafeController.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/controller/LocationController.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/controller/request/CafeRequest.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/entity/Cafe.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/entity/Location.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/repository/CafeRepository.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/repository/LocationRepository.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/service/CafeService.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/service/LocationService.java
Labels: ✨ Feature, 🔨 Refactor

#89 [bugfix/user/#88] 에러 해결
  cmap/src/main/resources/application.yml
Labels: 🐞 BugFix

#90 [feat/board-search/#82] 게시글 검색 및 페이지 작업 & token 적용
  cmap/src/main/java/com/umc/cmap/domain/board/controller/BoardController.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardListResponse.java
  cmap/src/main/java/com/umc/cmap/domain/board/repository/BoardRepository.java
  cmap/src/main/java/com/umc/cmap/domain/board/service/BoardService.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/repository/CafeRepository.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/controller/CmapController.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/entity/Cmap.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/entity/Type.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/repository/CmapRepository.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/service/CmapService.java
  cmap/src/main/java/com/umc/cmap/domain/comment/repository/CommentRepository.java
Labels: ✨ Feature

#91 [feat/cmap-mates/#85] cmap 유저의 메이트 가져오기
  cmap/Dockerfile
  cmap/src/main/java/com/umc/cmap/config/WebMvcConfig.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardPostViewResponse.java
  cmap/src/main/java/com/umc/cmap/domain/board/entity/Board.java
  cmap/src/main/java/com/umc/cmap/domain/board/service/BoardService.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/service/CmapService.java
  cmap/src/main/java/com/umc/cmap/domain/comment/repository/CommentRepository.java
  cmap/src/main/java/com/umc/cmap/domain/comment/service/CommentService.java
  cmap/src/main/java/com/umc/cmap/domain/review/dto/ReviewRequest.java
  cmap/src/main/java/com/umc/cmap/domain/review/dto/ReviewResponse.java
  cmap/src/main/java/com/umc/cmap/domain/review/entity/Review.java
  cmap/src/main/java/com/umc/cmap/domain/review/mapper/ReviewMapper.java
  cmap/src/main/java/com/umc/cmap/domain/review/service/ReviewService.java
  cmap/src/main/java/com/umc/cmap/file/S3Controller.java
  cmap/src/test/java/com/umc/cmap/domain/review/service/ReviewServiceTest.java
Labels: ✨ Feature

#87 [Feat/cafe/#86] cafetheme 기능 수정
  cmap/src/main/java/com/umc/cmap/config/BaseResponseStatus.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/controller/CafeController.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/entity/Cafe.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/repository/CafeRepository.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/service/CafeService.java
  cmap/src/main/java/com/umc/cmap/domain/filter/service/CafeFilterService.java
  cmap/src/main/java/com/umc/cmap/domain/theme/controller/CafeThemeController.java
  cmap/src/main/java/com/umc/cmap/domain/theme/controller/ThemeController.java
  cmap/src/main/java/com/umc/cmap/domain/theme/entity/CafeTheme.java
  cmap/src/main/java/com/umc/cmap/domain/theme/repository/ThemeRepository.java
  cmap/src/main/java/com/umc/cmap/domain/theme/service/CafeThemeService.java
  cmap/src/main/java/com/umc/cmap/domain/theme/service/ThemeService.java
Labels: ✨ Feature, 🔨 Refactor

#95 [feat/cmap-load/#74] Cmap want, went 기본 페이지 구현
  cmap/src/main/java/com/umc/cmap/config/BaseResponseStatus.java
  cmap/src/main/java/com/umc/cmap/domain/board/controller/BoardController.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardListResponse.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardPostViewResponse.java
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardResponse.java
  cmap/src/main/java/com/umc/cmap/domain/board/repository/BoardRepository.java
  cmap/src/main/java/com/umc/cmap/domain/board/service/BoardService.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/controller/CafeController.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/controller/LocationController.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/controller/request/CafeRequest.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/entity/Cafe.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/entity/Location.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/repository/CafeRepository.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/repository/LocationRepository.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/service/CafeService.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/service/LocationService.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/controller/CmapController.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/dto/CmapCafeDto.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/dto/CmapListResponse.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/repository/CmapRepository.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/service/CmapService.java
  cmap/src/main/java/com/umc/cmap/domain/comment/controller/CommentController.java
  cmap/src/main/java/com/umc/cmap/domain/comment/repository/CommentRepository.java
  cmap/src/main/java/com/umc/cmap/domain/comment/service/CommentService.java
  cmap/src/main/java/com/umc/cmap/domain/filter/service/CafeFilterService.java
  cmap/src/main/java/com/umc/cmap/domain/review/controller/ReviewController.java
  cmap/src/main/java/com/umc/cmap/domain/review/service/ReviewService.java
  cmap/src/main/java/com/umc/cmap/domain/theme/controller/CafeThemeController.java
  cmap/src/main/java/com/umc/cmap/domain/theme/controller/ThemeController.java
  cmap/src/main/java/com/umc/cmap/domain/theme/entity/CafeTheme.java
  cmap/src/main/java/com/umc/cmap/domain/theme/repository/ThemeRepository.java
  cmap/src/main/java/com/umc/cmap/domain/theme/service/CafeThemeService.java
  cmap/src/main/java/com/umc/cmap/domain/theme/service/ThemeService.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/controller/ProfileController.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/service/ProfileService.java
  cmap/src/main/resources/application.yml
Labels: ✨ Feature

#96 [Refactor/review api/#78] 리뷰 관련 전반적인 리팩토링
  cmap/src/main/java/com/umc/cmap/config/WebMvcConfig.java
  cmap/src/main/java/com/umc/cmap/config/excepion/ExceptionControllerAdvice.java
  cmap/src/main/java/com/umc/cmap/config/excepion/UnAuthorizedException.java
  cmap/src/main/java/com/umc/cmap/config/oauth/SecurityConfig.java
  cmap/src/main/java/com/umc/cmap/domain/comment/dto/CommentResponse.java
  cmap/src/main/java/com/umc/cmap/domain/review/controller/ReviewController.java
  cmap/src/main/java/com/umc/cmap/domain/review/dto/ReviewPreviewResponse.java
  cmap/src/main/java/com/umc/cmap/domain/review/dto/ReviewRequest.java
  cmap/src/main/java/com/umc/cmap/domain/review/dto/ReviewResponse.java
  cmap/src/main/java/com/umc/cmap/domain/review/entity/Review.java
  cmap/src/main/java/com/umc/cmap/domain/review/service/ReviewPreviewService.java
  cmap/src/main/java/com/umc/cmap/domain/review/service/ReviewService.java
  cmap/src/test/java/com/umc/cmap/domain/review/repository/ReviewRepositoryTest.java
  cmap/src/test/java/com/umc/cmap/domain/review/service/ReviewPreviewServiceTest.java
  cmap/src/test/java/com/umc/cmap/domain/review/service/ReviewServiceTest.java
Labels: 🔨 Refactor

#105 [Feat/cmap-save/#81] CMAP 저장 구현
  cmap/src/main/java/com/umc/cmap/config/oauth/SecurityConfig.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/controller/CafeStateController.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/dto/CmapStateRequest.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/entity/Cmap.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/mapper/CmapMapper.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/repository/CmapRepository.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/service/CafeStateService.java
Labels: ✨ Feature

#99 [Feat/cmap default/#92] cmap 디폴트
  cmap/src/main/java/com/umc/cmap/config/BaseResponseStatus.java
  cmap/src/main/java/com/umc/cmap/config/oauth/SecurityConfig.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/controller/CafeController.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/controller/response/CafeResponse.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/entity/Cafe.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/service/CafeService.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/controller/CmapController.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/dto/CmapCafeDto.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/dto/CmapDto.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/dto/CmapResponse.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/dto/CmapSearchResponse.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/entity/Cmap.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/repository/CmapRepository.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/service/CmapService.java
  cmap/src/main/java/com/umc/cmap/domain/filter/entity/CafeFilter.java
  cmap/src/main/java/com/umc/cmap/domain/filter/service/CafeFilterService.java
  cmap/src/main/java/com/umc/cmap/domain/review/repository/ReviewRepository.java
  cmap/src/main/java/com/umc/cmap/domain/review/service/ReviewService.java
  cmap/src/main/java/com/umc/cmap/domain/theme/controller/CafeThemeController.java
  cmap/src/main/java/com/umc/cmap/domain/theme/controller/request/CafeThemeRequest.java
  cmap/src/main/java/com/umc/cmap/domain/theme/service/CafeThemeService.java
Labels: ✨ Feature

#100 [feat/cmap-theme/#98] Cmap - want/went : theme 관련 기능 구현
  cmap/src/main/java/com/umc/cmap/domain/cafe/service/CafeService.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/controller/CmapController.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/dto/CmapCafeDto.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/dto/CmapListResponse.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/repository/CmapRepository.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/service/CmapService.java
  cmap/src/main/java/com/umc/cmap/domain/theme/repository/CafeThemeRepository.java
Labels: ✨ Feature, 🔨 Refactor

#102 [Refactor/profile/#94] 프로필 컨트롤러 수정 및 cafeTitle 추가
  cmap/src/main/java/com/umc/cmap/domain/user/entity/Profile.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/controller/ProfileController.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/dto/ProfileRequest.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/dto/ProfileResponse.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/service/ProfileService.java
Labels: 🔨 Refactor

#109 [feat/board/#101] 게시글 불러올 때 카페 인덱스 추가 (프론트 요청)
  cmap/src/main/java/com/umc/cmap/domain/board/dto/BoardPostViewResponse.java
Labels: ✨ Feature

#112 [Feat/users/#103] 전반적 수정 마지막(이길)
  cmap/src/main/java/com/umc/cmap/domain/user/login/controller/LoginController.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/token/OAuth2SuccessHandler.java
  cmap/src/main/java/com/umc/cmap/domain/user/login/token/TokenService.java
  cmap/src/main/java/com/umc/cmap/domain/user/mates/controller/MatesController.java
Labels: 🔨 Refactor

#113 [Feat/home/#110] 홈화면
  cmap/src/main/java/com/umc/cmap/config/oauth/SecurityConfig.java
  cmap/src/main/java/com/umc/cmap/domain/board/repository/BoardImageRepository.java
  cmap/src/main/java/com/umc/cmap/domain/board/repository/BoardRepository.java
  cmap/src/main/java/com/umc/cmap/domain/home/controller/HomeController.java
  cmap/src/main/java/com/umc/cmap/domain/home/dto/HomeResponse.java
  cmap/src/main/java/com/umc/cmap/domain/home/service/HomeService.java
Labels: ✨ Feature

#119 [Refactor/cafe/#118]검색 응답조건 수정
  cmap/src/main/java/com/umc/cmap/domain/cafe/controller/CafeController.java
  cmap/src/main/java/com/umc/cmap/domain/cafe/service/CafeService.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/controller/CmapController.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/service/CmapService.java
Labels: 🔨 Refactor

#123 [#120] refactor: modify cmap response
  cmap/src/main/java/com/umc/cmap/domain/cmap/dto/CmapCafeDto.java
  cmap/src/main/java/com/umc/cmap/domain/cmap/service/CmapService.java
Labels: 🔨 Refactor

#126 [refactor/users-login/#125] 프로필 response 수정
  cmap/src/main/java/com/umc/cmap/domain/user/profile/dto/ProfileRequest.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/dto/ProfileResponse.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/mapper/ProfileMapper.java
  cmap/src/main/java/com/umc/cmap/domain/user/profile/service/ProfileService.java
Labels: 🔨 Refactor

#124 [refactor/board/#122] 게시글 검색 기능 수정
  cmap/src/main/java/com/umc/cmap/domain/board/repository/BoardRepository.java
  cmap/src/main/java/com/umc/cmap/domain/board/service/BoardService.java
Labels: 🔨 Refactor

#127 [#122] refactor: modify profileImg
  cmap/src/main/java/com/umc/cmap/domain/board/service/BoardService.java
Labels: 🔨 Refactor
